### ISSUE TITLE
Forks Nomenclature

### ISSUE THREAD

**Issue by JayToDaBee** [JayToDaBee/TwelveAngryNodes_4.12#12]
Forks should be named with 2 Is and 1 O rather than 2 Os and 1 I.

If you don't want to do all symetric permutations yet, go for the IIO ordering (similarly to what you did for all other tiles, where I is before O in all symetric cases)

Example: SM_Hex_L_000000_IXOXOX_1 should be SM_Hex_L_000000_IXIXOX_1 (+permutations eventually)

**Comment by scaryrabbit** [comment]
Should be fixed. Let me know if there is any other issue with these forks.
