### ISSUE TITLE
Expose more map generation parameters

### ISSUE THREAD

**Issue by scaryrabbit** [JayToDaBee/TwelveAngryNodes_4.12#17]
Namely number of continents, continents size, etc.

These should be accessible through the map generation UI

**Comment by JayToDaBee** [comment]
Done. Didn't really bother to find an elegant way of going back to default values, but I wrote them out in parenthesis next to the new fields. If you feel this is sufficient feel free to close the issue (and possibly open a new one about creating a default values button or something)

**Comment by JayToDaBee** [comment]
Added a button to restore defaults in game setup screen
