### ISSUE TITLE
Cliffs V2

### ISSUE THREAD

**Issue by scaryrabbit** [JayToDaBee/TwelveAngryNodes_4.12#19]
New set of cliffs that will be separate from tiles.

**Comment by scaryrabbit** [comment]
![Cliff V2 wip](https://user-images.githubusercontent.com/6887591/104623537-797cc000-5660-11eb-9789-68caf74c7bad.png)

Looks like this so far. Starting inwards corners next.

**Comment by scaryrabbit** [comment]
![Cliff V2 wip2](https://user-images.githubusercontent.com/6887591/104648987-fb311580-5681-11eb-95b5-cd785b03f14f.png)

Finished all 4 basic pieces for cliffs. Now only need to do a variation of each with a waterfall.

**Comment by scaryrabbit** [comment]
![Cliff V2 wip3](https://user-images.githubusercontent.com/6887591/104795321-3a8f5d00-577b-11eb-8034-1b58eff1884c.png)

Finished all 4 waterfall cliffs.

**Comment by JayToDaBee** [comment]
Did you try playing a bit with making the waterfalls less linear, i.e. making them bounce off rocks etc? Or is this rather for a future iteration?

**Comment by scaryrabbit** [comment]
We'll keep that for future iterations. It shouldn't be hard to support variations on my end that would still mesh well with neighboring cliffs. I will close this issue and detail my naming convention in the TilesV3 issue instead to have everything centralized there.
