### ISSUE TITLE
Tool : Show most used tiles

### ISSUE THREAD

**Issue by scaryrabbit** [JayToDaBee/TwelveAngryNodes_4.12#7]
Create a tool to show which tiles are most frequently used in a generation and their count. Would be useful to know which tiles will require variants.

**Comment by JayToDaBee** [comment]
This is now doable on master by pressing (or rather releasing) the 'C' key once the map is generated. A file is created and you can read it out. Added an event for this in the player controller, but you can see if you want to do something a bit more involved with a button or an optionally appearing analytics window.

Anyways, if this all you wanted feel free to close the issue.
